### ISSUE TITLE
Bunny skips a step in the workflow

### ISSUE THREAD

**Issue by StarvingMarvin** [rabix/bunny#117]
In a very simple workflow second step gets ignores, and the output of the first step is returned as a result of the entire workflow:

https://gitlab.com/unduthegun/cwl-test/tree/master/rabix-2-steps

**Comment by milos-ljubinkovic** [comment]
rabix-2-steps/fails.cwl
- Creates only root/touch folder
- Logs "Job root.cat is completed."
- Doesn't log "Running command line: cat"

rabix-2-steps/passes.cwl
- Creates both folders and runs both commands


[cwltest.zip](https://github.com/rabix/bunny/files/754576/cwltest.zip)

**Comment by milos-ljubinkovic** [comment]
When the first step is over, OutputEventHandler triggers and looks for destination variables:

` List<VariableRecord> destinationVariables = variableService.find(link.getDestinationJobId(), link.getDestinationJobPort(), event.getContextId());`

In the "fails.cwl" case, this query returns both the input and output type VariableRecord objects for the second step and triggers both InputUpdateEvent and the OutputUpdateEvent with the same value, effectivly skipping the step.
