### ISSUE TITLE
Proper Bunny benchmarks

### ISSUE THREAD

**Issue by simonovic86** [rabix/bunny#122]
Create proper benchmarks for 1K, 2K and 5K WGS workflows with/without persistence.

**Comment by simonovic86** [comment]
I've created a simple batch mechanism which you can use in order to test properly. #129

**Comment by StarvingMarvin** [comment]
Final verdict: with postgresql persistence, on a laptop or mediocre aws instance, bunny can sustain throughput of ~ 80-100 jobs/s
