### ISSUE TITLE
Workflow valueFrom expression for a string input that gets a file

### ISSUE THREAD

**Issue by bogdang989** [rabix/bunny#130]
This is a weird one. Tool has a string input 'bam'. In the workflow this sting input gets a file. This is handled by JS expression in the workflow.

> - id: bam
>   source: bam
>   valueFrom: $(self.basename)

It seems like basename is not available for this input, so null is returned. Is this kind of handling in accordance with CWL spec in the first place?

**Comment by ntijanic** [comment]
Should be ok, though unconventional. Basename is possibly unset because it's not recognised as file (if the struct was created manually upstream) or it could be a bug. Will check.
