### ISSUE TITLE
Non-informative error message

### ISSUE THREAD

**Issue by kellrott** [rabix/bunny#134]
I'm trying to develop/debug the workflow https://github.com/OpenGenomics/mc3/blob/master/workflows/mc3_full.cwl 
cwltool can parse and start the workflow, but bunny gives a non-informative error:
```
/mnt/mc3/mc3$ ../rabix-1.0.0-rc2/rabix workflows/mc3_full.cwl
[2017-02-07 21:39:11.714] [ERROR] Error: file://workflows/mc3_full.cwl is not a valid app!
```

Not sure what bunny thinks is wrong with the workflow.

**Comment by ntijanic** [comment]
Hey Kyle,

it's an issue with our resolver that we've fixed on the default branch; we'll make a new release next week after we test out some other fixes. The error message is the generic one sadly; will improve those as well.

If you don't want to wait for the release, you can build from the default branch with `mvn clean install -P=all` and find the tar.gz archive in `./rabix-backend-local/target/`.

**Comment by StarvingMarvin** [comment]
Original issue should be fixed in rc3, and error message improvements are tracked through #102
