### ISSUE TITLE
Scattered nested workflow output when one job is created

### ISSUE THREAD

**Issue by bogdang989** [rabix/bunny#136]
Scattered nested workflow gets one file on input port used for scattering. Output of the nested workflow is a single file, instead of a list of files with length 1.

**Comment by sinisa88** [comment]
You are right. Here is test example.
[nested-scatter-wf.zip](https://github.com/rabix/bunny/files/768257/nested-scatter-wf.zip)

**Comment by simonovic86** [comment]
I've fixed it. It's already merged into develop and it will be included in the next release.

**Comment by bogdang989** [comment]
It's fixed, tnx
