### ISSUE TITLE
Randomly failing travis tests

### ISSUE THREAD

**Issue by milos-ljubinkovic** [rabix/bunny#152]
Conformance tests on Travis occasionally fails on some random workflow or tool that has file-type output. Usually running the tests again gets a different result.

Logs from 2 such subsequent runs.

[failed.txt](https://github.com/rabix/bunny/files/783622/failed.txt)
[passed.txt](https://github.com/rabix/bunny/files/783623/passed.txt)

thoughts:

- could be every first run on a new branch due to some issue related to the git clone -> mvn install flow

- isn't a race condition like the last travis issue because the failing test dir5 is used only once

- weird  `[34m[1m` string that shows up like corruption on the start of some lines of travis output in the failed log

**Comment by StarvingMarvin** [comment]
Weird string is terminal color code. Usually programs that output color logs detect they are not outputing to interactive terminal and output plain text. Not sure how could it be connected with failing, though.
