### ISSUE TITLE
READ.ME

### ISSUE THREAD

**Issue by stefanristeski** [rabix/bunny#16]
./rabix.sh -a example/grep-app.json -i example/grep-inputs.json is not valid anymore.

**Comment by duxan** [comment]
It seems working example is:

```
./rabix.sh examples/dna2protein/translate.cwl.json examples/dna2protein/inputs.json
```
without `-a` or `-i` swithes.

NOTE: form is actually `./rabix.sh <tool.json | .yaml>  <inputs.json | .yaml`, with emphasis on possibility to use YAML ;), its way easier to list inputs that way.

**Comment by gaurav-kaushik** [comment]
Thanks, guys. Submitted pull request to update README. Will update folder with more examples in next few days :)

**Comment by stefanristeski** [comment]
Np! :)

On Fri, Apr 22, 2016 at 7:00 PM, Gaurav Kaushik <notifications@github.com>
wrote:

> Thanks, guys. Submitted pull request to update README. Will update folder
> with more examples in next few days :)
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/rabix/bunny/issues/16#issuecomment-213512786>
>



-- 

*Stefan Risteski*
Bioinformatics Analyst

*Seven Bridges Genomics*
http://www.sbgenomics.com/
