### ISSUE TITLE
"Not a valid app" error is very vague

### ISSUE THREAD

**Issue by buchanae** [rabix/bunny#164]
When I run bunny on a CWL file that can't be loaded, I get an error like:
```
14:07:54.003 [main] ERROR o.r.backend.local.BackendCommandLine - Error: file://cwl-workflows/workflows/hello/hello-param-packed.cwl#main is not a valid app!
```

It would be helpful to have more exact details about what is wrong. I usually have to dig deep into the source of both the workflow and bunny in order to figure out what's going on.

**Comment by StarvingMarvin** [comment]
Yeah, it's truly hostile for trying out apps. We are working on it though: #102
