### ISSUE TITLE
Optional branch in the workflow

### ISSUE THREAD

**Issue by bogdang989** [rabix/bunny#177]
Workflow is separated into branches. Some of the branches receive no input. Branches are later merged. Tool that does the merge hangs as some of the branches are not yet executed.

**Comment by StarvingMarvin** [comment]
@bogdang989 can you please provide a link to the workflow.

**Comment by bogdang989** [comment]
Yup, here it is
[gdc-dnaseq-cwl-new.zip](https://github.com/rabix/bunny/files/813976/gdc-dnaseq-cwl-new.zip)

**Comment by StarvingMarvin** [comment]
So basically, it's not optional branch, it's scattering over empty list. We will probably make it return empty lists as a result, once we test edge cases regarding scattering on multiple ports

**Comment by StarvingMarvin** [comment]
Fix is merged to develop branch
