### ISSUE TITLE
refactored CWL conformance tests for stderr breaking on bunny

### ISSUE THREAD

**Issue by mr-c** [rabix/bunny#183]
See https://github.com/common-workflow-language/common-workflow-language/pull/400/files#diff-eb9bcd6d7aaa5dc861feeb30ea9db880

https://ci.commonwl.org/job/cwl-spec-pr/40/implementation=rabix,version=v1.0/testReport/

The files are created, but are empty

Can this be prioritized? It is blocking a few other improvements that we have in queue..

**Comment by StarvingMarvin** [comment]
Silly question: have the problem resolved itself, or is some action still needed? Locally all tests pass both with master and develop branches.
