### ISSUE TITLE
not pulling image from docker hub

### ISSUE THREAD

**Issue by davidroberson** [rabix/bunny#23]
I don't think it is correctly pulling the image down and is just running on local system.

**Comment by davidroberson** [comment]
My login is not root but is part of the docker group..the image has been pulled down manually.

**Comment by davidroberson** [comment]
...but bunny is working if I manually docker exec -it /bin/bash and run the cwl.json inside the container.

**Comment by sivkovic** [comment]
This should be fixed with the v0.4.0-alpha release. If you are pulling private docker image you should do a docker login on particular registry before running.
