### ISSUE TITLE
Command line is not properly escaped for one public Tool

### ISSUE THREAD

**Issue by AleksandarPetrovicSBG** [rabix/bunny#235]
Tool https://igor.sbgenomics.com/public/apps#admin/sbg-public-data/bwa-mem-bundle-0-7-13/ fails when used inside workflow. 
The error seems to be related to i<\\\\${len} fragment. On platform, generated command line looks like i<\${len} , but when ran from bunny, it turns into i<${len}

**Comment by StarvingMarvin** [comment]
I couldn't reproduce this issue.
