### ISSUE TITLE
Output directorory on the local backend

### ISSUE THREAD

**Issue by mattions** [rabix/bunny#239]
Hello, 

with rabix RC3, the local directory created when runnin ght job was callled:
`cwl_filename-<timestamp>`.

I saw, with RC5, we went back to have UUID instwad of that structure.

Any reason why it was killed?

**Comment by StarvingMarvin** [comment]
Accidental regression. Should be fixed for 1.0

**Comment by mattions** [comment]
@StarvingMarvin very cool :+1:

**Comment by milos-ljubinkovic** [comment]
This has been fixed in v1.0
