### ISSUE TITLE
Javascript comments // with spaces are not supported in Bunny

### ISSUE THREAD

**Issue by vladimirkovacevic** [rabix/bunny#274]
@savicm , @sinisa88

**Comment by sivkovic** [comment]
Sorry I accidentally clicked close. Do you maybe have the example of the app which fails?

**Comment by vladimirkovacevic** [comment]
@savicm said he is working on it, if I understood correctly?

**Comment by vladimirkovacevic** [comment]
Here is an example:
[fastqc.tool.txt](https://github.com/rabix/bunny/files/1084618/fastqc.tool.txt)
