### ISSUE TITLE
Glob does not catch files in the sub-directory (CWL 1.0)

### ISSUE THREAD

**Issue by vladimirkovacevic** [rabix/bunny#284]
[prepare_intervals.zip](https://github.com/rabix/bunny/files/1095304/prepare_intervals.zip)
25 BED files are created in Intervals subdirectory. 
Glob: Intervals/*.bed does not catch them. 
Another inconsistency, if the Glob is changed to:
*.bed 
it does catch them.

**Comment by milos-ljubinkovic** [comment]
The matching in CWLGlobServiceImpl is currently only done with the filename, not the whole path. This should probably be changed.
