### ISSUE TITLE
Add support for Docker-for-Mac

### ISSUE THREAD

**Issue by duxan** [rabix/bunny#33]
Hi,

New [docker for Mac](https://docs.docker.com/docker-for-mac/) uses OS X Hypervisor.framework for virtualization, instead of external virtualization programs. 

I tried bunny 0.6.4 with it and it gets stuck on pulling an image (manually pulling from shell works). Docker for Mac exposes the docker API on a socket in /var/tmp/docker.sock.

**Comment by gaurav-kaushik** [comment]
Hi, @duxan. I had a similar issue with Docker for Mac in an earlier version of bunny. Adding "export DOCKER_HOST=unix:///var/run/docker.sock" to ~./bash_profile fixed the issue for me. Not sure if this will work for you, but I am able to run the example workflow (dna2protein) with rabix-0.6.4 and Docker for Mac Version 1.12.1-rc1-beta23 (build: 11375)
2f0427ac7d4d47c705934ae141c3a248ed7fff40

**Comment by duxan** [comment]
It does work. Thanks @gaurav-kaushik!
