### ISSUE TITLE
Support for input files from multiple s3 providers

### ISSUE THREAD

**Issue by adamstruck** [rabix/bunny#418]
Input files should be allowed to come from more than one s3 provider

**Comment by adamstruck** [comment]
I also noticed that s3 providers without SSL are not supported

**Comment by milos-ljubinkovic** [comment]
I'm doing a rework of cloud integrations, will add seamless integration with multiple providers/buckets. Might have to write my own s3 lib, current one is too strict with providers requiring as you mentioned ssl and also that http requests/responses have no additional params.

**Comment by adamstruck** [comment]
I think ssl may be configurable via `s3fs_protocol`.  I think supporting multiple endpoints should be fairly trivial as well; perhaps we could add a field in the configuration in which you provide a list of s3 endpoints to support.
