### ISSUE TITLE
is it possible to use js expression engine to create files in the same way on SB?

### ISSUE THREAD

**Issue by davidroberson** [rabix/bunny#48]
would this work?

>"fileDef": 
              {
                "fileContent": {
                  "class": "Expression",
                  "script": "'#!/bin/bash \\n\\\n#/samtools/samtools view -H '+$job.inputs.bam.path+' > header.sam \\n\\\n\\n\\\n#filter for q20 \\n\\\n/samtools/samtools view -q 20 -b '+$job.inputs.bam.path+' > filtered.bam \\n\\\n\\n\\\n#cat header.sam filtered.bam > result.sam';\n",
                  "engine": "#cwl-js-engine"
                },
                "filename": "filter_for_q20.sh"
              }

**Comment by davidroberson** [comment]
Answered my own issue.  Yes this works perfectly.  I just needed to bake sure the bunny input.json  field names correctly matched what was in the workflow.cwl.json.  The workflow was expecting  `bam_files` and not just `bam`.

closed.

**Comment by ntijanic** [comment]
It works in draft-2 tools, but if you're using CWL1.0, you'll need to use [InitialWorkDirRequirement](http://www.commonwl.org/v1.0/UserGuide.html#Creating_files_at_runtime)
