### ISSUE TITLE
Tools with no input ports

### ISSUE THREAD

**Issue by davidroberson** [rabix/bunny#49]
Not the highest priority but tools that have no input ports might be causing an issue.  I have a tool which simply creates a .csv file which is input to another tool.  Works on SBG platform but maybe not locally with bunny.  

Issue is solved by putting the csv files in the second tool's wrapper.

Thanks

Dave

**Comment by ntijanic** [comment]
Hi Dave,

can you post here the link to the workflow on SB platform? Bunny should be able to reproduce all of the SB jobs, we'll look into it.

Thanks,

**Comment by davidroberson** [comment]
I still have to test this.  Just haven't had time.

Plus 1 👍 on the new release I will upgrade from 0.66  .  The inline command is a great addition.

**Comment by davidroberson** [comment]
To test all you need to do is make a pipeline that has an app which only creates a .csv file and then send that .csv on to another tool.  This tool does not have any inputs.  The reason for having it is to include the barcode manifest in the pipeline cwl.json description.  

Closing this issue because there are many ways around this and I have already adjusted the pipeline.

Thanks.
