### ISSUE TITLE
separate: false doesn't work for array input type

### ISSUE THREAD

**Issue by stefanristeski** [rabix/bunny#82]
On this example: http://www.commonwl.org/v1.0/UserGuide.html#Array_inputs
Bunny returns: "-C= seven,eight,nine"
Instead of: "-C=seven,eight,nine"

**Comment by simonovic86** [comment]
You're right, I've already fixed it. I'll create another release tomorrow.

**Comment by simonovic86** [comment]
It's fixed.

**Comment by stefanristeski** [comment]
@simonovic86 Fix is confirmed!
