### ISSUE TITLE
Path isn't properly mapped when running inside the container

### ISSUE THREAD

**Issue by StarvingMarvin** [rabix/bunny#86]
This time I can launch a cwl job with files and input not in the directory where rabix is:

```
mattions@apollo:rabix-1.0.0-rc2$ ./rabix ~/SBG/code/dna2protein/dna2protein.cwl.json -- --dna ~/SBG/code/dna2protein/dna.txt
[2016-12-16 14:32:22.807] [INFO] Pulling docker image sevenbridges/dna2protein:0.5.3
[2016-12-16 14:32:24.684] [INFO] Running command line: transcribe.py /home/mattions/SBG/code/dna2protein/dna.txt > transcribe.log
[2016-12-16 14:32:25.074] [INFO] Job root.transcribe has started
[2016-12-16 14:32:26.265] [ERROR] Job 66afc4ff-3162-4f2f-9f1a-1240525b52ca failed with exit code 2.
[2016-12-16 14:32:26.266] [INFO] Job 66afc4ff-3162-4f2f-9f1a-1240525b52ca failed with exit code 2.
[2016-12-16 14:32:27.190] [INFO] Failed to execute a Job
```

The job error
```
mattions@apollo:rabix-1.0.0-rc2$ cat dc1b8d30-f348-43dc-a1ad-133bf0cfbf4b/root/transcribe/job.err.log 
usage: transcribe.py [-h] [-v] [--version] dna
transcribe.py: error: argument dna: can't open '/home/mattions/SBG/code/dna2protein/dna.txt': [Errno 2] No such file or directory: '/home/mattions/SBG/code/dna2protein/dna.txt'
```

It looks like the file does not get mounted in the proper location in the container?

**Comment by StarvingMarvin** [comment]
@mattinos I still can't reproduce it. Are you sure you have a file dna.txt in that location? Is that input declared as a file or a string? Better yet, paste entire app, because dna2protein I'm using from the example works as expected.

**Comment by StarvingMarvin** [comment]
@mattions Actually, after few more tries, I've successfully reproduced it. It appears that the bug is in the handling of inputs that are in the parent directory of current directory.

**Comment by mattions** [comment]
@StarvingMarvin the app is here: https://github.com/sbg/dna2protein

**Comment by simonovic86** [comment]
I've successfully reproduced it too. I've fixed it and the change should be visible in the next release.

**Comment by StarvingMarvin** [comment]
@mattions Could you verify if rc3 release fixed your issues, and reopen if necessary?
