### ISSUE TITLE
Detect unconnected workflows

### ISSUE THREAD

**Issue by StarvingMarvin** [rabix/bunny#95]
I've accidentally created a workflow where output connections were declared as `source` instead of `outputSource`. The result was that after alls steps were executed, bunny hanged.

**Comment by milos-ljubinkovic** [comment]
It seems that OutputEventHandler is supposed to complete the job, but as the outputs are missing or malformed in this case, no OutputUpdateEvent is sent by the JobStatusEventHandler.

        for (PortCounter portCounter : jobRecord.getOutputCounters()) {
          Object output = event.getResult().get(portCounter.getPort());
          eventProcessor.addToQueue(new OutputUpdateEvent(jobRecord.getRootId(), jobRecord.getId(), portCounter.getPort(), output, 1, event.getEventGroupId()));
        }

Should the job fail in this case or should some code from the OutputEventHandler be moved to JobStatusEventHandler?

Please correct me if I make a bad assumption, I'm still feeling my way around the project and a lot of things are still completely unknown to me.

**Comment by simonovic86** [comment]
Let's sync up on this issue next week when we get back. The thing is that we should detect unconnected workflows before/during translation to the common DAG format.

We can modify **JobStatusEventHandler** to detect this and fail gracefully, but let's do the previous check first. I think that should be enough.

**Comment by StarvingMarvin** [comment]
The thing is we need to do both. There might be a valid app that doesn't have any outputs (say a custom uploader) and those would hang too.

**Comment by simonovic86** [comment]
I agree.
